// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(FruitShopRebornDbContext))]
    partial class FruitShopRebornDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Users.ShippingInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommuneWardCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .IsFixedLength();

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DetailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ShippingInformations");
                });

            modelBuilder.Entity("Core.Entities.Users.Staffs.StaffInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommuneWardCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .IsFixedLength();

                    b.Property<string>("DetailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .IsFixedLength();

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("IdentityNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("StaffInformations");
                });

            modelBuilder.Entity("Core.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.Users.Admin", b =>
                {
                    b.HasBaseType("Core.Entities.Users.User");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Core.Entities.Users.Customer", b =>
                {
                    b.HasBaseType("Core.Entities.Users.User");

                    b.Property<int>("DefaultShippingInformationId")
                        .HasColumnType("int");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Core.Entities.Users.Staffs.Staff", b =>
                {
                    b.HasBaseType("Core.Entities.Users.User");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffInformationId")
                        .HasColumnType("int");

                    b.HasIndex("StaffInformationId")
                        .IsUnique()
                        .HasFilter("[StaffInformationId] IS NOT NULL");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Core.Entities.Users.Staffs.Manager", b =>
                {
                    b.HasBaseType("Core.Entities.Users.Staffs.Staff");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Core.Entities.Users.Staffs.SalesStaff", b =>
                {
                    b.HasBaseType("Core.Entities.Users.Staffs.Staff");

                    b.ToTable("SalesStaffs");
                });

            modelBuilder.Entity("Core.Entities.Users.Staffs.Shipper", b =>
                {
                    b.HasBaseType("Core.Entities.Users.Staffs.Staff");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("Core.Entities.Users.ShippingInformation", b =>
                {
                    b.HasOne("Core.Entities.Users.Customer", "Customer")
                        .WithMany("ShippingInformations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Core.Entities.Users.Admin", b =>
                {
                    b.HasOne("Core.Entities.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Users.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Users.Customer", b =>
                {
                    b.HasOne("Core.Entities.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Users.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Users.Staffs.Staff", b =>
                {
                    b.HasOne("Core.Entities.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Users.Staffs.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Users.Staffs.StaffInformation", "StaffInformation")
                        .WithOne()
                        .HasForeignKey("Core.Entities.Users.Staffs.Staff", "StaffInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffInformation");
                });

            modelBuilder.Entity("Core.Entities.Users.Staffs.Manager", b =>
                {
                    b.HasOne("Core.Entities.Users.Staffs.Staff", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Users.Staffs.Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Users.Staffs.SalesStaff", b =>
                {
                    b.HasOne("Core.Entities.Users.Staffs.Staff", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Users.Staffs.SalesStaff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Users.Staffs.Shipper", b =>
                {
                    b.HasOne("Core.Entities.Users.Staffs.Staff", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Users.Staffs.Shipper", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Users.Customer", b =>
                {
                    b.Navigation("ShippingInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
